package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Attachments;
import com.example.redmine.db.model.AttachmentsExample;
import com.example.redmine.db.model.AttachmentsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(AttachmentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Attachments> selectByExample(AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Attachments selectByPrimaryKey(AttachmentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Attachments record, @Param("example") AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Attachments record, @Param("example") AttachmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Attachments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.attachments
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Attachments record);
}