package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Changes;
import com.example.redmine.db.model.ChangesExample;
import com.example.redmine.db.model.ChangesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChangesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(ChangesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(ChangesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(ChangesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Changes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Changes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Changes> selectByExample(ChangesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Changes selectByPrimaryKey(ChangesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Changes record, @Param("example") ChangesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Changes record, @Param("example") ChangesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Changes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changes
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Changes record);
}