package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Changesets;
import com.example.redmine.db.model.ChangesetsExample;
import com.example.redmine.db.model.ChangesetsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChangesetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(ChangesetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(ChangesetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(ChangesetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Changesets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Changesets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Changesets> selectByExample(ChangesetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Changesets selectByPrimaryKey(ChangesetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Changesets record, @Param("example") ChangesetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Changesets record, @Param("example") ChangesetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Changesets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.changesets
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Changesets record);
}