package com.example.redmine.db.mapper;

import com.example.redmine.db.model.CustomFields;
import com.example.redmine.db.model.CustomFieldsExample;
import com.example.redmine.db.model.CustomFieldsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomFieldsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(CustomFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(CustomFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(CustomFieldsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(CustomFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(CustomFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<CustomFields> selectByExample(CustomFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    CustomFields selectByPrimaryKey(CustomFieldsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") CustomFields record, @Param("example") CustomFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") CustomFields record, @Param("example") CustomFieldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(CustomFields record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(CustomFields record);
}