package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Documents;
import com.example.redmine.db.model.DocumentsExample;
import com.example.redmine.db.model.DocumentsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(DocumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(DocumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(DocumentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Documents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Documents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Documents> selectByExample(DocumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Documents selectByPrimaryKey(DocumentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Documents record, @Param("example") DocumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Documents record, @Param("example") DocumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Documents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.documents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Documents record);
}