package com.example.redmine.db.mapper;

import com.example.redmine.db.model.IssueStatuses;
import com.example.redmine.db.model.IssueStatusesExample;
import com.example.redmine.db.model.IssueStatusesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueStatusesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(IssueStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(IssueStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(IssueStatusesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(IssueStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(IssueStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<IssueStatuses> selectByExample(IssueStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    IssueStatuses selectByPrimaryKey(IssueStatusesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") IssueStatuses record, @Param("example") IssueStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") IssueStatuses record, @Param("example") IssueStatusesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(IssueStatuses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_statuses
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(IssueStatuses record);
}