package com.example.redmine.db.mapper;

import com.example.redmine.db.model.IssueCategories;
import com.example.redmine.db.model.IssueCategoriesExample;
import com.example.redmine.db.model.IssueCategoriesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueCategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(IssueCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(IssueCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(IssueCategoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(IssueCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(IssueCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<IssueCategories> selectByExample(IssueCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    IssueCategories selectByPrimaryKey(IssueCategoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") IssueCategories record, @Param("example") IssueCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") IssueCategories record, @Param("example") IssueCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(IssueCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_categories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(IssueCategories record);
}