package com.example.redmine.db.mapper;

import com.example.redmine.db.model.IssueRelations;
import com.example.redmine.db.model.IssueRelationsExample;
import com.example.redmine.db.model.IssueRelationsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueRelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(IssueRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(IssueRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(IssueRelationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(IssueRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(IssueRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<IssueRelations> selectByExample(IssueRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    IssueRelations selectByPrimaryKey(IssueRelationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") IssueRelations record, @Param("example") IssueRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") IssueRelations record, @Param("example") IssueRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(IssueRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issue_relations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(IssueRelations record);
}