package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Members;
import com.example.redmine.db.model.MembersExample;
import com.example.redmine.db.model.MembersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(MembersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Members record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Members record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Members> selectByExample(MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Members selectByPrimaryKey(MembersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Members record, @Param("example") MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Members record, @Param("example") MembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Members record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Members record);
}