package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Messages;
import com.example.redmine.db.model.MessagesExample;
import com.example.redmine.db.model.MessagesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(MessagesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Messages> selectByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Messages selectByPrimaryKey(MessagesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.messages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Messages record);
}