package com.example.redmine.db.mapper;

import com.example.redmine.db.model.OpenIdAuthenticationNonces;
import com.example.redmine.db.model.OpenIdAuthenticationNoncesExample;
import com.example.redmine.db.model.OpenIdAuthenticationNoncesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenIdAuthenticationNoncesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(OpenIdAuthenticationNoncesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(OpenIdAuthenticationNoncesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(OpenIdAuthenticationNoncesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(OpenIdAuthenticationNonces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(OpenIdAuthenticationNonces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<OpenIdAuthenticationNonces> selectByExample(OpenIdAuthenticationNoncesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    OpenIdAuthenticationNonces selectByPrimaryKey(OpenIdAuthenticationNoncesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") OpenIdAuthenticationNonces record, @Param("example") OpenIdAuthenticationNoncesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") OpenIdAuthenticationNonces record, @Param("example") OpenIdAuthenticationNoncesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(OpenIdAuthenticationNonces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_nonces
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(OpenIdAuthenticationNonces record);
}