package com.example.redmine.db.mapper;

import com.example.redmine.db.model.OpenIdAuthenticationAssociations;
import com.example.redmine.db.model.OpenIdAuthenticationAssociationsExample;
import com.example.redmine.db.model.OpenIdAuthenticationAssociationsKey;
import com.example.redmine.db.model.OpenIdAuthenticationAssociationsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenIdAuthenticationAssociationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(OpenIdAuthenticationAssociationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(OpenIdAuthenticationAssociationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(OpenIdAuthenticationAssociationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<OpenIdAuthenticationAssociationsWithBLOBs> selectByExampleWithBLOBs(OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<OpenIdAuthenticationAssociations> selectByExample(OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    OpenIdAuthenticationAssociationsWithBLOBs selectByPrimaryKey(OpenIdAuthenticationAssociationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") OpenIdAuthenticationAssociationsWithBLOBs record, @Param("example") OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OpenIdAuthenticationAssociationsWithBLOBs record, @Param("example") OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") OpenIdAuthenticationAssociations record, @Param("example") OpenIdAuthenticationAssociationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(OpenIdAuthenticationAssociationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OpenIdAuthenticationAssociationsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.open_id_authentication_associations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(OpenIdAuthenticationAssociations record);
}