package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Projects;
import com.example.redmine.db.model.ProjectsExample;
import com.example.redmine.db.model.ProjectsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(ProjectsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Projects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Projects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Projects> selectByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Projects selectByPrimaryKey(ProjectsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Projects record, @Param("example") ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Projects record, @Param("example") ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Projects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Projects record);
}