package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Queries;
import com.example.redmine.db.model.QueriesExample;
import com.example.redmine.db.model.QueriesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QueriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(QueriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(QueriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(QueriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Queries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Queries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Queries> selectByExample(QueriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Queries selectByPrimaryKey(QueriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Queries record, @Param("example") QueriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Queries record, @Param("example") QueriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Queries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.queries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Queries record);
}