package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Repositories;
import com.example.redmine.db.model.RepositoriesExample;
import com.example.redmine.db.model.RepositoriesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(RepositoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(RepositoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(RepositoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Repositories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Repositories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Repositories> selectByExample(RepositoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Repositories selectByPrimaryKey(RepositoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Repositories record, @Param("example") RepositoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Repositories record, @Param("example") RepositoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Repositories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.repositories
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Repositories record);
}