package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Versions;
import com.example.redmine.db.model.VersionsExample;
import com.example.redmine.db.model.VersionsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(VersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(VersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(VersionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Versions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Versions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Versions> selectByExample(VersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Versions selectByPrimaryKey(VersionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Versions record, @Param("example") VersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Versions record, @Param("example") VersionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Versions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.versions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Versions record);
}