package com.example.redmine.db.mapper;

import com.example.redmine.db.model.WikiContents;
import com.example.redmine.db.model.WikiContentsExample;
import com.example.redmine.db.model.WikiContentsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(WikiContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(WikiContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(WikiContentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(WikiContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(WikiContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<WikiContents> selectByExample(WikiContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    WikiContents selectByPrimaryKey(WikiContentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") WikiContents record, @Param("example") WikiContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") WikiContents record, @Param("example") WikiContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(WikiContents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_contents
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(WikiContents record);
}