package com.example.redmine.db.mapper;

import com.example.redmine.db.model.WikiPages;
import com.example.redmine.db.model.WikiPagesExample;
import com.example.redmine.db.model.WikiPagesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiPagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(WikiPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(WikiPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(WikiPagesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(WikiPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(WikiPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<WikiPages> selectByExample(WikiPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    WikiPages selectByPrimaryKey(WikiPagesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") WikiPages record, @Param("example") WikiPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") WikiPages record, @Param("example") WikiPagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(WikiPages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wiki_pages
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(WikiPages record);
}