package com.example.redmine.db.mapper;

import com.example.redmine.db.model.Workflows;
import com.example.redmine.db.model.WorkflowsExample;
import com.example.redmine.db.model.WorkflowsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkflowsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(WorkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(WorkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(WorkflowsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Workflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Workflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Workflows> selectByExample(WorkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Workflows selectByPrimaryKey(WorkflowsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Workflows record, @Param("example") WorkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Workflows record, @Param("example") WorkflowsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Workflows record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.workflows
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Workflows record);
}