package com.example.redmine.db.model;

import java.util.Date;

public class Attachments extends AttachmentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.container_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer containerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.container_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String containerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.disk_filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String diskFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.filesize
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.content_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.digest
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.downloads
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer downloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.author_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.attachments.disk_directory
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String diskDirectory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.container_id
     *
     * @return the value of public.attachments.container_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getContainerId() {
        return containerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.container_id
     *
     * @param containerId the value for public.attachments.container_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setContainerId(Integer containerId) {
        this.containerId = containerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.container_type
     *
     * @return the value of public.attachments.container_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getContainerType() {
        return containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.container_type
     *
     * @param containerType the value for public.attachments.container_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setContainerType(String containerType) {
        this.containerType = containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.filename
     *
     * @return the value of public.attachments.filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.filename
     *
     * @param filename the value for public.attachments.filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.disk_filename
     *
     * @return the value of public.attachments.disk_filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDiskFilename() {
        return diskFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.disk_filename
     *
     * @param diskFilename the value for public.attachments.disk_filename
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDiskFilename(String diskFilename) {
        this.diskFilename = diskFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.filesize
     *
     * @return the value of public.attachments.filesize
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.filesize
     *
     * @param filesize the value for public.attachments.filesize
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.content_type
     *
     * @return the value of public.attachments.content_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.content_type
     *
     * @param contentType the value for public.attachments.content_type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.digest
     *
     * @return the value of public.attachments.digest
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDigest() {
        return digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.digest
     *
     * @param digest the value for public.attachments.digest
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.downloads
     *
     * @return the value of public.attachments.downloads
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getDownloads() {
        return downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.downloads
     *
     * @param downloads the value for public.attachments.downloads
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDownloads(Integer downloads) {
        this.downloads = downloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.author_id
     *
     * @return the value of public.attachments.author_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.author_id
     *
     * @param authorId the value for public.attachments.author_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.created_on
     *
     * @return the value of public.attachments.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.created_on
     *
     * @param createdOn the value for public.attachments.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.description
     *
     * @return the value of public.attachments.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.description
     *
     * @param description the value for public.attachments.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.attachments.disk_directory
     *
     * @return the value of public.attachments.disk_directory
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDiskDirectory() {
        return diskDirectory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.attachments.disk_directory
     *
     * @param diskDirectory the value for public.attachments.disk_directory
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDiskDirectory(String diskDirectory) {
        this.diskDirectory = diskDirectory;
    }
}