package com.example.redmine.db.model;

import java.util.ArrayList;
import java.util.List;

public class CustomFieldsTrackersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public CustomFieldsTrackersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustomFieldIdIsNull() {
            addCriterion("custom_field_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdIsNotNull() {
            addCriterion("custom_field_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdEqualTo(Integer value) {
            addCriterion("custom_field_id =", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdNotEqualTo(Integer value) {
            addCriterion("custom_field_id <>", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdGreaterThan(Integer value) {
            addCriterion("custom_field_id >", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("custom_field_id >=", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdLessThan(Integer value) {
            addCriterion("custom_field_id <", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdLessThanOrEqualTo(Integer value) {
            addCriterion("custom_field_id <=", value, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdIn(List<Integer> values) {
            addCriterion("custom_field_id in", values, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdNotIn(List<Integer> values) {
            addCriterion("custom_field_id not in", values, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdBetween(Integer value1, Integer value2) {
            addCriterion("custom_field_id between", value1, value2, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andCustomFieldIdNotBetween(Integer value1, Integer value2) {
            addCriterion("custom_field_id not between", value1, value2, "customFieldId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdIsNull() {
            addCriterion("tracker_id is null");
            return (Criteria) this;
        }

        public Criteria andTrackerIdIsNotNull() {
            addCriterion("tracker_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrackerIdEqualTo(Integer value) {
            addCriterion("tracker_id =", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdNotEqualTo(Integer value) {
            addCriterion("tracker_id <>", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdGreaterThan(Integer value) {
            addCriterion("tracker_id >", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tracker_id >=", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdLessThan(Integer value) {
            addCriterion("tracker_id <", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdLessThanOrEqualTo(Integer value) {
            addCriterion("tracker_id <=", value, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdIn(List<Integer> values) {
            addCriterion("tracker_id in", values, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdNotIn(List<Integer> values) {
            addCriterion("tracker_id not in", values, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdBetween(Integer value1, Integer value2) {
            addCriterion("tracker_id between", value1, value2, "trackerId");
            return (Criteria) this;
        }

        public Criteria andTrackerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tracker_id not between", value1, value2, "trackerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 05 22:10:02 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.custom_fields_trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}