package com.example.redmine.db.model;

import java.util.Date;

public class Documents extends DocumentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.documents.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.documents.category_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.documents.title
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.documents.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.documents.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Date createdOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.documents.project_id
     *
     * @return the value of public.documents.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.documents.project_id
     *
     * @param projectId the value for public.documents.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.documents.category_id
     *
     * @return the value of public.documents.category_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.documents.category_id
     *
     * @param categoryId the value for public.documents.category_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.documents.title
     *
     * @return the value of public.documents.title
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.documents.title
     *
     * @param title the value for public.documents.title
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.documents.description
     *
     * @return the value of public.documents.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.documents.description
     *
     * @param description the value for public.documents.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.documents.created_on
     *
     * @return the value of public.documents.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.documents.created_on
     *
     * @param createdOn the value for public.documents.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
}