package com.example.redmine.db.model;

public class GroupsUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.groups_users.group_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.groups_users.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.groups_users.group_id
     *
     * @return the value of public.groups_users.group_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.groups_users.group_id
     *
     * @param groupId the value for public.groups_users.group_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.groups_users.user_id
     *
     * @return the value of public.groups_users.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.groups_users.user_id
     *
     * @param userId the value for public.groups_users.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}