package com.example.redmine.db.model;

public class OpenIdAuthenticationNoncesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.open_id_authentication_nonces.id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.open_id_authentication_nonces.id
     *
     * @return the value of public.open_id_authentication_nonces.id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.open_id_authentication_nonces.id
     *
     * @param id the value for public.open_id_authentication_nonces.id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }
}