package com.example.redmine.db.model;

import java.util.Date;

public class Projects extends ProjectsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.homepage
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String homepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.is_public
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Boolean isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.parent_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.updated_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Date updatedOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.status
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.lft
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer lft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.rgt
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer rgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.inherit_members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Boolean inheritMembers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.name
     *
     * @return the value of public.projects.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.name
     *
     * @param name the value for public.projects.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.description
     *
     * @return the value of public.projects.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.description
     *
     * @param description the value for public.projects.description
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.homepage
     *
     * @return the value of public.projects.homepage
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.homepage
     *
     * @param homepage the value for public.projects.homepage
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.is_public
     *
     * @return the value of public.projects.is_public
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.is_public
     *
     * @param isPublic the value for public.projects.is_public
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.parent_id
     *
     * @return the value of public.projects.parent_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.parent_id
     *
     * @param parentId the value for public.projects.parent_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.created_on
     *
     * @return the value of public.projects.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.created_on
     *
     * @param createdOn the value for public.projects.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.updated_on
     *
     * @return the value of public.projects.updated_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Date getUpdatedOn() {
        return updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.updated_on
     *
     * @param updatedOn the value for public.projects.updated_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.identifier
     *
     * @return the value of public.projects.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.identifier
     *
     * @param identifier the value for public.projects.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.status
     *
     * @return the value of public.projects.status
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.status
     *
     * @param status the value for public.projects.status
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.lft
     *
     * @return the value of public.projects.lft
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getLft() {
        return lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.lft
     *
     * @param lft the value for public.projects.lft
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setLft(Integer lft) {
        this.lft = lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.rgt
     *
     * @return the value of public.projects.rgt
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getRgt() {
        return rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.rgt
     *
     * @param rgt the value for public.projects.rgt
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setRgt(Integer rgt) {
        this.rgt = rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.inherit_members
     *
     * @return the value of public.projects.inherit_members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Boolean getInheritMembers() {
        return inheritMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.inherit_members
     *
     * @param inheritMembers the value for public.projects.inherit_members
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setInheritMembers(Boolean inheritMembers) {
        this.inheritMembers = inheritMembers;
    }
}