package com.example.redmine.db.model;

public class Queries extends QueriesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.filters
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String filters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.column_names
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String columnNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.sort_criteria
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String sortCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.group_by
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String groupBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries.options
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String options;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.project_id
     *
     * @return the value of public.queries.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.project_id
     *
     * @param projectId the value for public.queries.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.name
     *
     * @return the value of public.queries.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.name
     *
     * @param name the value for public.queries.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.filters
     *
     * @return the value of public.queries.filters
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getFilters() {
        return filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.filters
     *
     * @param filters the value for public.queries.filters
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setFilters(String filters) {
        this.filters = filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.user_id
     *
     * @return the value of public.queries.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.user_id
     *
     * @param userId the value for public.queries.user_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.column_names
     *
     * @return the value of public.queries.column_names
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getColumnNames() {
        return columnNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.column_names
     *
     * @param columnNames the value for public.queries.column_names
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setColumnNames(String columnNames) {
        this.columnNames = columnNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.sort_criteria
     *
     * @return the value of public.queries.sort_criteria
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getSortCriteria() {
        return sortCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.sort_criteria
     *
     * @param sortCriteria the value for public.queries.sort_criteria
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setSortCriteria(String sortCriteria) {
        this.sortCriteria = sortCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.group_by
     *
     * @return the value of public.queries.group_by
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getGroupBy() {
        return groupBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.group_by
     *
     * @param groupBy the value for public.queries.group_by
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setGroupBy(String groupBy) {
        this.groupBy = groupBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.type
     *
     * @return the value of public.queries.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.type
     *
     * @param type the value for public.queries.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.visibility
     *
     * @return the value of public.queries.visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.visibility
     *
     * @param visibility the value for public.queries.visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries.options
     *
     * @return the value of public.queries.options
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries.options
     *
     * @param options the value for public.queries.options
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setOptions(String options) {
        this.options = options;
    }
}