package com.example.redmine.db.model;

public class QueriesRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries_roles.query_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.queries_roles.role_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries_roles.query_id
     *
     * @return the value of public.queries_roles.query_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries_roles.query_id
     *
     * @param queryId the value for public.queries_roles.query_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setQueryId(Integer queryId) {
        this.queryId = queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.queries_roles.role_id
     *
     * @return the value of public.queries_roles.role_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.queries_roles.role_id
     *
     * @param roleId the value for public.queries_roles.role_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}