package com.example.redmine.db.model;

import java.util.Date;

public class Repositories extends RepositoriesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.login
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.password
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.root_url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String rootUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.path_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String pathEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.log_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String logEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.extra_info
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String extraInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.is_default
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.repositories.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Date createdOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.project_id
     *
     * @return the value of public.repositories.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.project_id
     *
     * @param projectId the value for public.repositories.project_id
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.url
     *
     * @return the value of public.repositories.url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.url
     *
     * @param url the value for public.repositories.url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.login
     *
     * @return the value of public.repositories.login
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.login
     *
     * @param login the value for public.repositories.login
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.password
     *
     * @return the value of public.repositories.password
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.password
     *
     * @param password the value for public.repositories.password
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.root_url
     *
     * @return the value of public.repositories.root_url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getRootUrl() {
        return rootUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.root_url
     *
     * @param rootUrl the value for public.repositories.root_url
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setRootUrl(String rootUrl) {
        this.rootUrl = rootUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.type
     *
     * @return the value of public.repositories.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.type
     *
     * @param type the value for public.repositories.type
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.path_encoding
     *
     * @return the value of public.repositories.path_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getPathEncoding() {
        return pathEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.path_encoding
     *
     * @param pathEncoding the value for public.repositories.path_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setPathEncoding(String pathEncoding) {
        this.pathEncoding = pathEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.log_encoding
     *
     * @return the value of public.repositories.log_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getLogEncoding() {
        return logEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.log_encoding
     *
     * @param logEncoding the value for public.repositories.log_encoding
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setLogEncoding(String logEncoding) {
        this.logEncoding = logEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.extra_info
     *
     * @return the value of public.repositories.extra_info
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getExtraInfo() {
        return extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.extra_info
     *
     * @param extraInfo the value for public.repositories.extra_info
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setExtraInfo(String extraInfo) {
        this.extraInfo = extraInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.identifier
     *
     * @return the value of public.repositories.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.identifier
     *
     * @param identifier the value for public.repositories.identifier
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.is_default
     *
     * @return the value of public.repositories.is_default
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.is_default
     *
     * @param isDefault the value for public.repositories.is_default
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.repositories.created_on
     *
     * @return the value of public.repositories.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.repositories.created_on
     *
     * @param createdOn the value for public.repositories.created_on
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
}