package com.example.redmine.db.model;

public class Roles extends RolesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.position
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.assignable
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Boolean assignable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.builtin
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private Integer builtin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.permissions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String permissions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.roles.issues_visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    private String issuesVisibility;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.name
     *
     * @return the value of public.roles.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.name
     *
     * @param name the value for public.roles.name
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.position
     *
     * @return the value of public.roles.position
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.position
     *
     * @param position the value for public.roles.position
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.assignable
     *
     * @return the value of public.roles.assignable
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Boolean getAssignable() {
        return assignable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.assignable
     *
     * @param assignable the value for public.roles.assignable
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setAssignable(Boolean assignable) {
        this.assignable = assignable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.builtin
     *
     * @return the value of public.roles.builtin
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public Integer getBuiltin() {
        return builtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.builtin
     *
     * @param builtin the value for public.roles.builtin
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setBuiltin(Integer builtin) {
        this.builtin = builtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.permissions
     *
     * @return the value of public.roles.permissions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getPermissions() {
        return permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.permissions
     *
     * @param permissions the value for public.roles.permissions
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.roles.issues_visibility
     *
     * @return the value of public.roles.issues_visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public String getIssuesVisibility() {
        return issuesVisibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.roles.issues_visibility
     *
     * @param issuesVisibility the value for public.roles.issues_visibility
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    public void setIssuesVisibility(String issuesVisibility) {
        this.issuesVisibility = issuesVisibility;
    }
}