package com.example.redmine.db.sql;

import com.example.redmine.db.model.Boards;
import com.example.redmine.db.model.BoardsExample;
import com.example.redmine.db.model.BoardsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BoardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(BoardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(BoardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(BoardsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Boards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Boards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Boards> selectByExample(BoardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Boards selectByPrimaryKey(BoardsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Boards record, @Param("example") BoardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Boards record, @Param("example") BoardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Boards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.boards
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Boards record);
}