package com.example.redmine.db.sql;

import com.example.redmine.db.model.CustomFieldsProjects;
import com.example.redmine.db.model.CustomFieldsProjectsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomFieldsProjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(CustomFieldsProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(CustomFieldsProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(CustomFieldsProjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(CustomFieldsProjects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<CustomFieldsProjects> selectByExample(CustomFieldsProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") CustomFieldsProjects record, @Param("example") CustomFieldsProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.custom_fields_projects
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") CustomFieldsProjects record, @Param("example") CustomFieldsProjectsExample example);
}