package com.example.redmine.db.sql;

import com.example.redmine.db.model.Enumerations;
import com.example.redmine.db.model.EnumerationsExample;
import com.example.redmine.db.model.EnumerationsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnumerationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(EnumerationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(EnumerationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(EnumerationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Enumerations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Enumerations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Enumerations> selectByExample(EnumerationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Enumerations selectByPrimaryKey(EnumerationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Enumerations record, @Param("example") EnumerationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Enumerations record, @Param("example") EnumerationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Enumerations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.enumerations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Enumerations record);
}