package com.example.redmine.db.sql;

import com.example.redmine.db.model.Issues;
import com.example.redmine.db.model.IssuesExample;
import com.example.redmine.db.model.IssuesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(IssuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(IssuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(IssuesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Issues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Issues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Issues> selectByExample(IssuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Issues selectByPrimaryKey(IssuesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Issues record, @Param("example") IssuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Issues record, @Param("example") IssuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Issues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.issues
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Issues record);
}