package com.example.redmine.db.sql;

import com.example.redmine.db.model.JournalDetails;
import com.example.redmine.db.model.JournalDetailsExample;
import com.example.redmine.db.model.JournalDetailsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JournalDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(JournalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(JournalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(JournalDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(JournalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(JournalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<JournalDetails> selectByExample(JournalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    JournalDetails selectByPrimaryKey(JournalDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") JournalDetails record, @Param("example") JournalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") JournalDetails record, @Param("example") JournalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(JournalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journal_details
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(JournalDetails record);
}