package com.example.redmine.db.sql;

import com.example.redmine.db.model.Journals;
import com.example.redmine.db.model.JournalsExample;
import com.example.redmine.db.model.JournalsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JournalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(JournalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(JournalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(JournalsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Journals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Journals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Journals> selectByExample(JournalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Journals selectByPrimaryKey(JournalsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Journals record, @Param("example") JournalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Journals record, @Param("example") JournalsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Journals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.journals
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Journals record);
}