package com.example.redmine.db.sql;

import com.example.redmine.db.model.MemberRoles;
import com.example.redmine.db.model.MemberRolesExample;
import com.example.redmine.db.model.MemberRolesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(MemberRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(MemberRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(MemberRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(MemberRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(MemberRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<MemberRoles> selectByExample(MemberRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    MemberRoles selectByPrimaryKey(MemberRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") MemberRoles record, @Param("example") MemberRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") MemberRoles record, @Param("example") MemberRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(MemberRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(MemberRoles record);
}