package com.example.redmine.db.sql;

import com.example.redmine.db.model.Roles;
import com.example.redmine.db.model.RolesExample;
import com.example.redmine.db.model.RolesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(RolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Roles> selectByExample(RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Roles selectByPrimaryKey(RolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Roles record, @Param("example") RolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Roles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.roles
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Roles record);
}