package com.example.redmine.db.sql;

import com.example.redmine.db.model.SchemaMigrations;
import com.example.redmine.db.model.SchemaMigrationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchemaMigrationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(SchemaMigrationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(SchemaMigrationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(SchemaMigrations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(SchemaMigrations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<SchemaMigrations> selectByExample(SchemaMigrationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") SchemaMigrations record, @Param("example") SchemaMigrationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.schema_migrations
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") SchemaMigrations record, @Param("example") SchemaMigrationsExample example);
}