package com.example.redmine.db.sql;

import com.example.redmine.db.model.TimeEntries;
import com.example.redmine.db.model.TimeEntriesExample;
import com.example.redmine.db.model.TimeEntriesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeEntriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(TimeEntriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(TimeEntriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(TimeEntriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(TimeEntries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(TimeEntries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<TimeEntries> selectByExample(TimeEntriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    TimeEntries selectByPrimaryKey(TimeEntriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") TimeEntries record, @Param("example") TimeEntriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") TimeEntries record, @Param("example") TimeEntriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(TimeEntries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.time_entries
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(TimeEntries record);
}