package com.example.redmine.db.sql;

import com.example.redmine.db.model.Tokens;
import com.example.redmine.db.model.TokensExample;
import com.example.redmine.db.model.TokensKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokensMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(TokensKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Tokens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Tokens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Tokens> selectByExample(TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Tokens selectByPrimaryKey(TokensKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Tokens record, @Param("example") TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Tokens record, @Param("example") TokensExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Tokens record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tokens
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Tokens record);
}