package com.example.redmine.db.sql;

import com.example.redmine.db.model.Trackers;
import com.example.redmine.db.model.TrackersExample;
import com.example.redmine.db.model.TrackersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrackersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(TrackersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(TrackersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(TrackersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Trackers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Trackers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Trackers> selectByExample(TrackersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Trackers selectByPrimaryKey(TrackersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Trackers record, @Param("example") TrackersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Trackers record, @Param("example") TrackersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Trackers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.trackers
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Trackers record);
}