package com.example.redmine.db.sql;

import com.example.redmine.db.model.UserPreferences;
import com.example.redmine.db.model.UserPreferencesExample;
import com.example.redmine.db.model.UserPreferencesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPreferencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(UserPreferencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(UserPreferencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(UserPreferencesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(UserPreferences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(UserPreferences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<UserPreferences> selectByExample(UserPreferencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    UserPreferences selectByPrimaryKey(UserPreferencesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") UserPreferences record, @Param("example") UserPreferencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") UserPreferences record, @Param("example") UserPreferencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(UserPreferences record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_preferences
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(UserPreferences record);
}