package com.example.redmine.db.sql;

import com.example.redmine.db.model.Wikis;
import com.example.redmine.db.model.WikisExample;
import com.example.redmine.db.model.WikisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int countByExample(WikisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByExample(WikisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int deleteByPrimaryKey(WikisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insert(Wikis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int insertSelective(Wikis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    List<Wikis> selectByExample(WikisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    Wikis selectByPrimaryKey(WikisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExampleSelective(@Param("record") Wikis record, @Param("example") WikisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByExample(@Param("record") Wikis record, @Param("example") WikisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKeySelective(Wikis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.wikis
     *
     * @mbggenerated Sun Jun 05 22:10:02 JST 2016
     */
    int updateByPrimaryKey(Wikis record);
}